# Generated by Django 4.0.6 on 2022-07-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='defence',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='dribble',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='pace',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='passing',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='phyical',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='shoot',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill_move',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='weak_foot',
            field=models.CharField(max_length=20),
        ),
    ]
