# Generated by Django 3.1.12 on 2022-07-27 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import squad.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Squad', max_length=20)),
                ('formation', models.CharField(choices=[('4-4-2', 'F442'), ('4-3-3', 'F433'), ('4-1-2-1-2', 'F41212'), ('3-5-2', 'F352')], default='4-4-2', max_length=20)),
                ('players', djongo.models.fields.ArrayField(default=[], model_container=squad.models.player_in_sqaud, model_form_class=squad.models.AuthorForm)),
                ('own_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
